### ISSUE TITLE
Error message when using plugin

### ISSUE THREAD

**Issue by alexvandervegt** [MunifTanjim/node-bitbucket#17]
You are setting an error and info message in console when we use your plugin:

error:  BITBUCKET CLOUD API CHANGING NOTICE:  https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr 
info:  BITBUCKET CLOUD API MIGRATION GUIDE:  https://developer.atlassian.com/cloud/bitbucket/bbc-gdpr-api-migration-guide 

Please make them both info, since error messages will fail when you try to build the code in google firebase cloud functions

This are the lines in your index.js. Please make them both console.info or remove it entirely and just quote this lines in the readme.

console.warn(
  `\x1b[43m\x1b[30m %s \x1b[0m\x1b[33m %s \x1b[0m`,
  `BITBUCKET CLOUD API CHANGING NOTICE:`,
  `https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr`
)

console.info(
  '\x1b[46m\x1b[30m %s \x1b[0m\x1b[36m %s \x1b[0m',
  `BITBUCKET CLOUD API MIGRATION GUIDE:`,
  `https://developer.atlassian.com/cloud/bitbucket/bbc-gdpr-api-migration-guide`
)

**Comment by MunifTanjim** [comment]
@alexivkin Thanks for reporting this.

I've just published v[`1.8.1`](https://www.npmjs.com/package/bitbucket/v/1.8.1) :tada: 

Now those notice will use `console.log` instead of `console.warn` or `console.info`.

In case you already know about those notice and don't want them to clutter your console, you can use the `hideNotice` options while creating the bitbucket instance, like this:

```js
new BitBucket({ hideNotice: true })
```

Hope that helps.

**Comment by alexvandervegt** [comment]
Thanks, but i still get errors:

Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: /user_code/node_modules/bitbucket/src/request/request-options.js:24
    ...remainingOptions
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/bitbucket/src/request/index.js:1:89)

**Comment by alexvandervegt** [comment]
I updated nodejs to version 8 and it works, thanks for your time!  :)
